apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: udacity
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: canary
    # version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80